Imports System.ComponentModel
Imports Microsoft.Office.Interop
Imports System.IO

Public Class InventoryHistory

    Public Sub refreshDataGridInvHist()

        Me.dataviewInvHist.Rows.Clear()
        dataviewInvHist.RowTemplate.Height = 40

        ConnectDatabase()

        With sqlcmd

            Try
                .Connection = DBConnection
                .CommandType = CommandType.StoredProcedure
                .CommandText = "viewInventoryHist"
                .Parameters.AddWithValue("@SuppID", InventoryList.InventorySupplyID)
                'MsgBox("Successful", MsgBoxStyle.Information, "Information")

                myreader = sqlcmd.ExecuteReader

                While myreader.Read()

                    Me.dataviewInvHist.Rows.Add(New Object() {myreader("InventoryID"), myreader("SupplyName"), myreader("initialStock"), myreader("RemainingStock"), myreader("Unit"), myreader("Remarks"), myreader("DateLastUpdated")})

                End While

            Catch ex As Exception
                MsgBox(ex.Message, MsgBoxStyle.Critical, "Error")
            End Try

        End With

        DatabaseDisconnect()

    End Sub



    Private Sub InventoryHistory_Load(sender As Object, e As EventArgs) Handles Me.Load
        txtboxProductName.Text = EditInventory.txtboxSupplyName.Text
        refreshDataGridInvHist()

    End Sub

    Private Sub InventoryHistory_Closing(sender As Object, e As CancelEventArgs) Handles Me.Closing

        EditInventory.Enabled = True

    End Sub

    Private Sub dataviewInvHist_CellMouseMove(sender As Object, e As DataGridViewCellMouseEventArgs) Handles dataviewInvHist.CellMouseMove

        dataviewInvHist.ClearSelection()
        If e.RowIndex > -1 Then
            dataviewInvHist.Rows(e.RowIndex).Selected = True
        End If

    End Sub


    Private Sub btnExcel_Click(sender As Object, e As EventArgs) Handles btnExcel.Click


        Dim StartUpPath As String = Application.StartupPath


        Dim xlsFiles As String = desktopPath + "\Dental Clinic Management System\Reports\InventoryRecords\"
        Dim xlsTemplates As String

        If StartUpPath.Contains("bin") Then
            xlsTemplates = StartUpPath.Replace("\bin\Debug\net6.0-windows\", "\Templates\")
        Else
            xlsTemplates = StartUpPath + "\Templates\"
        End If

        'MsgBox(xlsTemplates)
        'MsgBox(xlsFiles)

        Dim xlsApp As Excel.Application
        Dim xlsWB As Excel.Workbook
        Dim xlsSheet As Excel.Worksheet

        xlsApp = New Excel.Application

        xlsApp.Visible = False
        xlsWB = xlsApp.Workbooks.Open(xlsTemplates & "InventoryRecordPerSupply.xlsx")

        xlsSheet = xlsWB.Worksheets(1)
        xlsSheet.Unprotect("flair")

        Dim x As Integer
        Dim currentRow As Integer = 9
        For x = 0 To dataviewInvHist.RowCount - 1

            xlsSheet.Cells(currentRow, 1) = dataviewInvHist.Rows(x).Cells("colSupplyName").Value
            xlsSheet.Cells(currentRow, 2) = dataviewInvHist.Rows(x).Cells("colInitialStock").Value
            xlsSheet.Cells(currentRow, 3) = dataviewInvHist.Rows(x).Cells("colNewBalance").Value
            xlsSheet.Cells(currentRow, 4) = dataviewInvHist.Rows(x).Cells("colStockUnit").Value
            xlsSheet.Cells(currentRow, 5) = dataviewInvHist.Rows(x).Cells("colRemarks").Value
            xlsSheet.Cells(currentRow, 6) = dataviewInvHist.Rows(x).Cells("colDateUpdated").Value.ToString

            currentRow += 1

        Next

        xlsSheet.Cells(3, 1) = txtboxProductName.Text + " - INVENTORY RECORD"
        xlsSheet.Cells(5, 6) = dataviewInvHist.Rows.Count.ToString

        With xlsSheet.Range("A9", "E" & currentRow - 1)
            .Borders(Excel.XlBordersIndex.xlInsideHorizontal).LineStyle = Excel.XlLineStyle.xlContinuous
            .Borders(Excel.XlBordersIndex.xlInsideHorizontal).Weight = Excel.XlBorderWeight.xlHairline
        End With

        xlsSheet.PageSetup.Orientation = Excel.XlPageOrientation.xlLandscape
        xlsApp.ActiveWindow.View = Excel.XlWindowView.xlPageLayoutView
        xlsApp.ActiveWindow.DisplayGridlines = False

        xlsSheet.PageSetup.LeftFooter = "Date Created: " & DateTime.Now & Chr(10) & "Generated by: " & LoginAccount.empName

        Dim myfilename As String = txtboxProductName.Text + "-InventoryRecord-" & DateTime.Now.ToString("MMddyy-HHmmss") & ".xlsx"
        xlsSheet.Protect("flair")

        xlsWB.SaveAs(xlsFiles & myfilename)
        xlsApp.Quit()

        releaseObject(xlsApp)
        releaseObject(xlsWB)
        releaseObject(xlsSheet)

        If File.Exists("C:\Program Files (x86)\Microsoft Office\root\Office16\EXCEL.EXE") Then

            Process.Start("C:\Program Files (x86)\Microsoft Office\root\Office16\EXCEL.EXE", """" & xlsFiles & myfilename & """")

        ElseIf File.Exists("C:\Program Files\Microsoft Office\root\Office16\EXCEL.EXE") Then

            Process.Start("C:\Program Files\Microsoft Office\root\Office16\EXCEL.EXE", """" & xlsFiles & myfilename & """")

        Else

            MessageBox.Show("Excel is not installed in this device", "Warning", MessageBoxButtons.OK, MessageBoxIcon.Exclamation)

        End If

    End Sub


End Class
